### ISSUE TITLE
do not stop when a "MySQL has gone away" error pops

### ISSUE THREAD

**Issue by ninsuo** [redcall-io/app#294]
Integrate the https://github.com/facile-it/doctrine-mysql-come-back library in RedCall.

It should be as easy as adding the library and the following configuration:

```
                wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection'
                driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
                options:
                    x_reconnect_attempts: 3
```

_edit_: looks not working on GCP, should investigate why.

![Screenshot 2020-05-10 at 19 22 28](https://user-images.githubusercontent.com/4152132/81505993-b7685e00-92f3-11ea-95cd-ec8b94342f62.png)
